## Домашнее задание по блоку 09.03.2021. Библиотека NumPy
### Тихонова Инна

In [1]:
import numpy as np

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
n = 10
np.array([n-i-1 for i in np.arange(n)])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
n = 10

a = np.eye(n)
b = np.array([n-i-1 for i in np.arange(n)])

c = a * b
c

array([[9., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
c.sum()

45.0

**Задание 3**

Решите систему уравнений:

 - 4x + 2y + z = 4
 - x + 3y = 12
 - 5y + 4z = -3

In [20]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [22]:
x = np.linalg.solve(a, b)
x

array([ 0.46666667,  3.84444444, -5.55555556])

In [23]:
np.allclose(np.dot(a, x), b)

True

**Задание 4**

Имеется матрица покупок в интернет-магазине. Индекс строки - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [26]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [27]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [28]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [30]:
close_users = []

for user in users_stats:
    close_users.append(cosine(next_user_stats, user))
    
close_users    

[0.19999999999999996,
 0.8451542547285165,
 0.3999999999999999,
 0.7905694150420948,
 0.3999999999999999,
 0.0,
 0.0,
 0.9486832980505138,
 0.0,
 0.0]

Нам нужен максимально близкий к новому пользователю -> между векторами должен быть наименьший угол -> нужен максимальный косинус.

In [37]:
close_users.index(max(close_users))

7